package rules

dialect "java"

import org.futures.model.Commodity;
import org.futures.model.AvailableRegion;

rule "Coffee Arabica"
    agenda-group "commodity-rules"
when
    $c : Commodity(name=="Arabica")
then
    insert(new AvailableRegion("Brasil","Minas Gerais"));
    insert(new AvailableRegion("Brasil","São Paulo"));
    insert(new AvailableRegion("Brasil","Bahia"));
    insert(new AvailableRegion("Colombia","Andina Cafeeira"));
    System.out.println("Arabica detected");
end

rule "Coffee Robusta"
    agenda-group "commodity-rules"
when
    $c : Commodity(name=="Robusta")
then
    insert(new AvailableRegion("Brasil","Espirito Santo"));
    insert(new AvailableRegion("Vietnam","Central Highlands"));
    System.out.println("Robusta detected");
end