package rules

dialect "java"

import org.futures.model.ExchangeRate;
import org.futures.model.PartialSignal;
import org.futures.model.Hypothesis;
import org.futures.model.Commodity;
import java.util.Map;
import java.util.HashMap;

rule "Local currency depreciation - Brasil"
when
    $commodity :Commodity(name in ("Arabica","Robusta"))
    $er : ExchangeRate(country=="Brasil",month==$commodity.getMonth())
    eval($er.getVariation()>=1.5)
then
    double confidence=0.0;
    switch ($commodity.getName()) {
        case "Arabica": confidence=0.91; break;
        case "Robusta": confidence=0.83; break;
    }

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Fall of the local currency compared to the dollar",factors,confidence,"SELL"));
    System.out.println("Local currency depreciation - country=" + $er.getCountry() +", month=" + $commodity.getMonth() +", exchangeRateVariation=" + $er.getVariation() +", action=SELL");
end

rule "Local currency depreciation - Colombia"
when
    $commodity :Commodity(name in ("Arabica"))
    $er : ExchangeRate(country=="Colombia",month==$commodity.getMonth())
    eval($er.getVariation()>=1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Fall of the local currency compared to the dollar",factors,0.7,"SELL"));
    System.out.println("Local currency depreciation - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=SELL");
end

rule "Local currency depreciation - Vietnam"
when
    $commodity :Commodity(name in ("Robusta"))
    $er : ExchangeRate(country=="Vietnam",month==$commodity.getMonth())
    eval($er.getVariation()>=1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Fall of the local currency compared to the dollar",factors,0.8,"SELL"));
    System.out.println("Local currency depreciation - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=SELL");
end

rule "Local currency strengthening - Brasil"
when
    $commodity :Commodity(name in ("Arabica","Robusta"))
    $er : ExchangeRate(country=="Brasil",month==$commodity.getMonth())
    eval($er.getVariation()<=-1.5)
then
    double confidence=0.0;
    switch ($commodity.getName()) {
        case "Arabica": confidence=0.91; break;
        case "Robusta": confidence=0.83; break;
    }
    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Rise of the local currency compared to the dollar",factors,confidence,"BUY"));
    System.out.println("Local currency strengthening - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=BUY");
end

rule "Local currency strengthening - Colombia"
when
    $commodity :Commodity(name in ("Arabica"))
    $er : ExchangeRate(country=="Colombia",month==$commodity.getMonth())
    eval($er.getVariation()<=-1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Rise of the local currency compared to the dollar",factors,0.7,"BUY"));
    System.out.println("Local currency strengthening - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=BUY");
end

rule "Local currency strengthening - Vietnam"
when
    $commodity :Commodity(name in ("Robusta"))
    $er : ExchangeRate(country=="Vietnam",month==$commodity.getMonth())
    eval($er.getVariation()<=-1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Rise of the local currency compared to the dollar",factors,0.8,"BUY"));
    System.out.println("Local currency strengthening - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=BUY");
end

rule "Local currency stabilization - Brasil"
when
    $commodity :Commodity(name in ("Arabica","Robusta"))
    $er : ExchangeRate(country=="Brasil",month==$commodity.getMonth())
    eval(-1.5<$er.getVariation() && $er.getVariation()<1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Stabilization of the local currency compared to the dollar",factors,0.4,"HOLD"));
    System.out.println("Local currency stabilization - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=HOLD");
end

rule "Local currency stabilization - Colombia"
when
    $commodity :Commodity(name in ("Arabica"))
    $er : ExchangeRate(country=="Colombia",month==$commodity.getMonth())
    eval(-1.5<$er.getVariation() && $er.getVariation()<1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Stabilization of the local currency compared to the dollar",factors,0.4,"HOLD"));
    System.out.println("Local currency stabilization - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=HOLD");
end


rule "Local currency stabilization - Vietnam"
when
    $commodity :Commodity(name in ("Robusta"))
    $er : ExchangeRate(country=="Vietnam",month==$commodity.getMonth())
    eval(-1.5<$er.getVariation() && $er.getVariation()<1.5)
then

    Map<String, Object> factors = new HashMap<>();
    factors.put("exchangeRateVariation", $er.getVariation());
    factors.put("month", $commodity.getMonth());
    factors.put("country", $er.getCountry());

    insert(new Hypothesis($commodity.getName(),"Stabilization of the local currency compared to the dollar",factors,0.4,"HOLD"));
    System.out.println("Local currency stabilization - country=" + $er.getCountry() + ", month=" + $commodity.getMonth() + ", exchangeRateVariation=" + $er.getVariation() + ", action=HOLD");
end

