package rules;
dialect "java"

import org.futures.model.Commodity;
import org.futures.model.Hypothesis;
import org.futures.model.MarketPerception;
import org.futures.model.AvailableRegion;
import java.util.Map;
import java.util.HashMap;

rule "Positive Perception"
when
    $commodity: Commodity(name in ("Arabica","Robusta"))
    $mp : MarketPerception(perception=="Positive",intensity>=0.6,commodity==$commodity.getName(),month==$commodity.getMonth())
    exists(AvailableRegion(country==$mp.getCountry()))
then
    double confidence=0.00;
    switch($commodity.getName()) {
        case "Arabica":
            switch ($mp.getCountry()){
                case "Brasil":
                        confidence=0.53;
                    break;
                case "Colombia":
                        confidence=0.42;
                    break;
            }
            break;
        case "Robusta":
            switch ($mp.getCountry()){
                case "Brasil":
                        confidence=0.45;
                    break;
                case "Vietnam":
                        confidence=0.56;
                    break;
            }
            break;
    }

    Map<String, Object> factors = new HashMap<>();
    factors.put("perception", $mp.getPerception());
    factors.put("intensity", $mp.getIntensity());
    factors.put("source", $mp.getSource());
    factors.put("description", $mp.getDescription());
    factors.put("month", $mp.getMonth());
    factors.put("country", $mp.getCountry());

    insert(new Hypothesis($commodity.getName(),"Positive Perception",factors,confidence,"BUY"));
    System.out.println("Positive Perception - country=" + $mp.getCountry() + ", month=" + $mp.getMonth() + ", commodity=" + $mp.getCommodity() + ", perception=" + $mp.getPerception() + ", intensity=" + $mp.getIntensity() + ", description=" + $mp.getDescription());
end

rule "Negative Perception"
when
    $commodity: Commodity(name in ("Arabica","Robusta"))
    $mp : MarketPerception(perception=="Negative",intensity>=0.6,commodity==$commodity.getName(),month==$commodity.getMonth())
    exists(AvailableRegion(country==$mp.getCountry()))
then

    double confidence=0.00;
    switch($commodity.getName()) {
        case "Arabica":
            switch ($mp.getCountry()){
                case "Brasil":
                        confidence=0.53;
                    break;
                case "Colombia":
                        confidence=0.42;
                    break;
            }
            break;
        case "Robusta":
            switch ($mp.getCountry()){
                case "Brasil":
                        confidence=0.45;
                    break;
                case "Vietnam":
                        confidence=0.56;
                    break;
            }
            break;
    }
    Map<String, Object> factors = new HashMap<>();
    factors.put("perception", $mp.getPerception());
    factors.put("intensity", $mp.getIntensity());
    factors.put("source", $mp.getSource());
    factors.put("description", $mp.getDescription());
    factors.put("month", $mp.getMonth());
    factors.put("country", $mp.getCountry());

    insert(new Hypothesis($commodity.getName(),"Negative Perception",factors,confidence,"SELL"));
    System.out.println("Negative Perception - country=" + $mp.getCountry() + ", month=" + $mp.getMonth() + ", commodity=" + $mp.getCommodity() + ", perception=" + $mp.getPerception() + ", intensity=" + $mp.getIntensity() + ", description=" + $mp.getDescription());
end

rule "Neutral Perception"
when
    $commodity: Commodity(name in ("Arabica","Robusta"))
    $mp : MarketPerception(intensity<0.6,commodity==$commodity.getName(),month==$commodity.getMonth())
    exists(AvailableRegion(country==$mp.getCountry()))
then
    double confidence=0.00;
    switch($commodity.getName()) {
        case "Arabica":
            switch ($mp.getCountry()){
                case "Brasil":
                        confidence=0.53;
                    break;
                case "Colombia":
                        confidence=0.42;
                    break;
            }
            break;
        case "Robusta":
            switch ($mp.getCountry()){
                case "Brasil":
                        confidence=0.45;
                    break;
                case "Vietnam":
                        confidence=0.56;
                    break;
            }
            break;
    }
    Map<String, Object> factors = new HashMap<>();
    factors.put("perception", $mp.getPerception());
    factors.put("intensity", $mp.getIntensity());
    factors.put("source", $mp.getSource());
    factors.put("description", $mp.getDescription());
    factors.put("month", $mp.getMonth());
    factors.put("country", $mp.getCountry());

    insert(new Hypothesis($commodity.getName(),"Neutral Perception",factors,confidence,"HOLD"));
    System.out.println("Neutral Perception - country=" + $mp.getCountry() + ", month=" + $mp.getMonth() + ", commodity=" + $mp.getCommodity() + ", perception=" + $mp.getPerception() + ", intensity=" + $mp.getIntensity() + ", description=" + $mp.getDescription());
end
