package rules

dialect "java"

import org.futures.model.Production;
import org.futures.model.PartialSignal;
import org.futures.model.Hypothesis;
import org.futures.model.Commodity;
import org.futures.model.AvailableRegion;
import java.util.Map;
import java.util.HashMap;

rule "Production Low - Brasil Arabica"
    agenda-group "arabica"
when
    $commodity :Commodity(name=="Arabica")
    $p : Production(country=="Brasil",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()<=5)
then
    double confidence=0.0;
    switch ($r.getRegion()){
        case "Minas Gerais": confidence=0.93;break;
        case "São Paulo": confidence=0.82;break;
        case "Bahia": confidence=0.6;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Low Production on Brasil",factors,confidence,"SELL"));

    System.out.println("Low production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", action=SELL");
end

rule "Production Low - Colombia Arabica"
    agenda-group "arabica"
when
    $commodity :Commodity(name=="Arabica")
    $p : Production(country=="Colombia",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()<=5)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Andina Cafeeira": confidence=0.86;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Low Production on Colombia",factors,confidence,"SELL"));

    System.out.println("Low production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", action=SELL");
end

rule "Production Low - Brasil Robusta"
    agenda-group "robusta"
when
    $commodity :Commodity(name=="Robusta")
    $p : Production(country=="Brasil",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()<=5)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Espirito Santo": confidence=0.77;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Low Production on Brasil",factors,confidence,"SELL"));
    System.out.println("Low production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=SELL");
end

rule "Production Low - Vietnam Robusta"
    agenda-group "robusta"
when
    $commodity :Commodity(name=="Robusta")
    $p : Production(country=="Vietnam",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()<=5)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Central Highlands": confidence=0.95;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Low Production on Vietnam",factors,confidence,"SELL"));

    System.out.println("Low production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=SELL");
end

rule "Average Production - Brasil Arabica"
    agenda-group "arabica"
when
    $commodity :Commodity(name=="Arabica")
    $p : Production(country=="Brasil",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval(5<$p.getProduction() && $p.getProduction()<=25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Minas Gerais": confidence=0.93;break;
        case "São Paulo": confidence=0.82;break;
        case "Bahia": confidence=0.6;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Average Production on Brasil",factors,confidence,"HOLD"));

    System.out.println("Average production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=HOLD");
end

rule "Average Production - Colombia Arabica"
    agenda-group "arabica"
when
    $commodity :Commodity(name=="Arabica")
    $p : Production(country=="Colombia",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval(5<$p.getProduction() && $p.getProduction()<=25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Andina Cafeeira": confidence=0.86;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Average Production on Colombia",factors,confidence,"HOLD"));

    System.out.println("Average production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=HOLD");
end

rule "Average Production - Brasil Robusta"
    agenda-group "robusta"
when
    $commodity :Commodity(name=="Robusta")
    $p : Production(country=="Brasil",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval(5<$p.getProduction() && $p.getProduction()<=25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Espirito Santo": confidence=0.77;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Average Production on Brasil",factors,confidence,"HOLD"));

    System.out.println("Average production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=HOLD");
end

rule "Average Production - Vietnam Robusta"
    agenda-group "robusta"
when
    $commodity :Commodity(name=="Robusta")
    $p : Production(country=="Vietnam",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r : AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval(5<$p.getProduction() && $p.getProduction()<=25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Central Highlands": confidence=0.95;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"Average Production on Vietnam",factors,confidence,"HOLD"));

    System.out.println("Average production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=HOLD");
end

rule "High Production - Brasil Arabica"
    agenda-group "arabica"
when
    $commodity :Commodity(name=="Arabica")
    $p : Production(country=="Brasil",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()>25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Minas Gerais": confidence=0.93;break;
        case "São Paulo": confidence=0.82;break;
        case "Bahia": confidence=0.6;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"High Production on Brasil",factors,confidence,"BUY"));

    System.out.println("High production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=BUY");
end

rule "High Production - Colombia Arabica"
    agenda-group "arabica"
when
    $commodity :Commodity(name=="Arabica")
    $p : Production(country=="Colombia",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()>25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Andina Cafeeira": confidence=0.86;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"High Production on Colombia",factors,confidence,"BUY"));

    System.out.println("High production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=BUY");
end

rule "High Production - Brasil Robusta"
    agenda-group "robusta"
when
    $commodity :Commodity(name=="Robusta")
    $p : Production(country=="Brasil",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()>25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Espirito Santo": confidence=0.77;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"High Production on Brasil",factors,confidence,"BUY"));

    System.out.println("High production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=BUY");
end

rule "High Production - Vietnam Robusta"
    agenda-group "robusta"
when
    $commodity :Commodity(name=="Robusta")
    $p : Production(country=="Vietnam",month==$commodity.getMonth(),commodity==$commodity.getName())
    $r: AvailableRegion(country==$p.getCountry(),region==$p.getRegion())
    eval($p.getProduction()>25)
then
    double confidence=0.0;
    switch ($p.getRegion()){
        case "Central Highlands": confidence=0.95;break;
    }

    Map<String,Object> factors = new HashMap<>();
    factors.put("country", $p.getCountry());
    factors.put("region", $p.getRegion());
    factors.put("month", $p.getMonth());
    factors.put("production", $p.getProduction());

    insert(new Hypothesis($p.getCommodity(),"High Production on Vietnam",factors,confidence,"BUY"));

    System.out.println("High production detected - country=" + $p.getCountry() +", region=" + $p.getRegion() +", commodity=" + $p.getCommodity() +", month=" + $p.getMonth() +", production=" + $p.getProduction() +", confidence=" + confidence +", action=BUY");
end
